[package]
name = "flatc-build-example"
version = "0.1.0"
authors = ["Toshiki Teramura <toshiki.teramura@gmail.com>"]
edition = "2018"

[dependencies.flatbuffers]
path = "../flatbuffers"

[build-dependencies]
cmake = "0.1"
